### ISSUE TITLE
Add a table containing name of contributers in Contributing.md

### ISSUE THREAD

**Issue by ok-open-sc** [ok-open-sc/Sorting_algo#7]
This is a good first issue for new comers who want to start contributing to open source, 
Simply edit the Contributing.md 

For New-Comers:
https://www.markdownguide.org/cheat-sheet/ take this as a reference, Happy Hacking

**Comment by droffilc1** [comment]
I would like to contribute to this issue..

**Comment by AmirMahdyTurani** [comment]
Hi dear @ok-open-sc.
i would like contribute this issue. As I understand it, the purpose of this issue is to have a table containing name and github link columns in the Contributing.md. If you need anything more, please let me know.
Thank You.

**Comment by ok-open-sc** [comment]
There is no assigns for this, if your contribution will be ok, your pull req. will be merged @droffilc1 @AmirMahdyTurani

**Comment by droffilc1** [comment]
@ok-open-sc  Okay
